packages:
  - .
  - packages/*

allowBuilds:
  '@tailwindcss/oxide': true
  dprint: true
  esbuild: true
  sharp: true
  workerd: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - dprint
  - esbuild
  - sharp
  - workerd
