// This file is auto-generated by the generate-icons-index.js script.
// Do not edit this file directly. Run 'pnpm generate-icons' to update it.
// Generated on 2026-04-02T00:05:05.338Z
export { default as GithubLogo } from "./github-logo.svg";
export { default as GitlabLogo } from "./gitlab-logo.svg";
export { default as NodejsLogo } from "./nodejs-logo.svg";
export { default as PythonLogo } from "./python-logo.svg";
