// This file is auto-generated by the generate-icons-index.js script.
// Do not edit this file directly. Run 'pnpm generate-icons' to update it.
//
// Placeholder: will be populated with 1,521 SVG re-exports in Phase 2.
