/**
 * Shiki transformer that injects additional Tailwind CSS classes into highlighted block nodes.
 *
 * This transformer augments the `<pre>` and `<code>` elements produced by Shiki during syntax
 * highlighting. It merges caller-provided Tailwind classes with any existing classes already
 * present on the nodes.
 *
 * ## Behavior
 *
 * - Existing classes are preserved and maintain their original relative order.
 * - New classes are appended only if they are not already present.
 * - Class values are normalized into whitespace-separated tokens.
 * - Both `class` and `className` properties are supported as input.
 * - The final result is written to `className`.
 * - Any legacy `class` property is removed.
 *
 * This approach ensures compatibility with different HTML AST producers while avoiding duplicate
 * Tailwind utilities.
 *
 * ## Normalization
 *
 * All class inputs are normalized using {@link toClassTokens}:
 *
 * - strings are split on whitespace
 * - arrays are flattened and tokenized
 * - falsy values are ignored
 *
 * The merged class list is written back via {@link assignMergedClassName}.
 *
 * ## Typical use cases
 *
 * - applying consistent layout utilities to Shiki blocks
 * - enforcing typography or spacing utilities
 * - adding framework-specific styling hooks
 *
 * ## Example
 *
 * ```ts
 * import { applyTailwindClasses } from "./tailwind-class-transformer";
 *
 * const transformer = applyTailwindClasses({
 *   pre: "rounded-lg border border-zinc-200 dark:border-zinc-700",
 *   code: ["font-mono", "text-sm"],
 * });
 *
 * shiki.codeToHtml(source, {
 *   lang: "ts",
 *   transformers: [transformer],
 * });
 * ```
 *
 * @see {@link assignMergedClassName}
 * @see {@link toClassTokens}
 */

import type { ShikiTransformer } from "shiki";
import {
    assignMergedClassName,
    type ClassableNode,
    type ClassValue,
    toClassTokens,
} from "./class-tokens";

/**
 * Options for {@link applyTailwindClasses}.
 */
export interface TailwindClassTransformerOptions {
    /**
     * Extra classes applied to the outer `<pre>` element generated by Shiki.
     *
     * Accepted forms:
     *
     * - whitespace-separated string
     * - array of strings
     *
     * Examples:
     *
     * ```ts
     * pre: "rounded-lg border"
     * pre: ["rounded-lg", "border"]
     * ```
     *
     * Values are normalized into class tokens before merging.
     */
    pre?: ClassValue;

    /**
     * Extra classes applied to the inner `<code>` element generated by Shiki.
     *
     * Accepted forms:
     *
     * - whitespace-separated string
     * - array of strings
     *
     * Examples:
     *
     * ```ts
     * code: "font-mono text-sm"
     * code: ["font-mono", "text-sm"]
     * ```
     *
     * Values are normalized into class tokens before merging.
     */
    code?: ClassValue;
}

/**
 * Creates a small adapter that applies class merging to a Shiki node.
 *
 * The returned function is used as a Shiki transformer hook (`pre` or `code`). If no classes were
 * provided, the function exits early.
 */
const applyClasses = (extras: readonly string[]) => (node: ClassableNode): void => {
    if (extras.length === 0) return;
    assignMergedClassName(node, extras);
};

/**
 * Builds a Shiki transformer that injects Tailwind CSS classes into highlighted code blocks.
 *
 * The transformer participates in Shiki's AST transformation pipeline and runs for both the
 * `<pre>` and `<code>` nodes generated during highlighting.
 *
 * ## Guarantees
 *
 * - class tokens remain unique
 * - original class order is preserved
 * - injected classes are appended deterministically
 * - both `class` and `className` input properties are supported
 *
 * ## Design goals
 *
 * - predictable Tailwind integration
 * - compatibility with multiple HTML AST producers
 * - minimal runtime overhead
 * - stable class ordering for deterministic rendering
 *
 * @param options configuration controlling which classes are injected
 * @returns a {@link ShikiTransformer} that merges Tailwind classes into block nodes
 */
export function applyTailwindClasses({
    pre = [],
    code = [],
}: TailwindClassTransformerOptions): ShikiTransformer {
    const preClasses = toClassTokens(pre);
    const codeClasses = toClassTokens(code);

    return {
        name: "tailwind-class-injector",
        pre: applyClasses(preClasses),
        code: applyClasses(codeClasses),
    } satisfies ShikiTransformer;
}
