export {
    getMostCitedBooks,
    getMostCitedReferences,
    getReferenceById,
    getReferencesByTag,
    getReferencesForLesson,
    getReferenceStats,
    getUsagesForReference,
    loadBibliographyCatalog,
} from "./catalog";
export { parseBibliography, resolveReferenceGroups } from "./normalize-jsonld";
export type {
    AuthorRef,
    BibliographyCatalog,
    BibliographyJsonLd,
    BookCitationStat,
    CatalogLesson,
    CatalogUsage,
    GetReferencesForLessonOptions,
    GetReferenceStatsOptions,
    LessonReferenceEntry,
    LessonReferenceGroups,
    LoadBibliographyCatalogOptions,
    NormalizedArticleReference,
    NormalizedBookReference,
    NormalizedReference,
    NormalizedThesisReference,
    NormalizedWebReference,
    ParseBibliographyOptions,
    ParsedBibliography,
    ReferenceStat,
    ReferenceTag,
    ResolvedReferenceGroups,
    ResolveGroupsOptions,
    SupportedReferenceType,
} from "./types";
